name: leak-check

on:
  push:
    branches: [ "master", "preparation" ]
  pull_request:
    branches: [ "master", "preparation" ]
  workflow_dispatch:

jobs:
  leak-check:
    name: leak-check
    runs-on: ubuntu-latest
    steps:
      - name: fetch-repo
        uses: actions/checkout@v3

      - name: secret-scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: false
          GITLEAKS_ENABLE_SUMMARY: true
        continue-on-error: true
